StTest <- function(LD)
{
  library(readxl)
  library(data.table)
  library(ggplot2)
  library(ggsignif)
  outline <- read_excel("summary.xls")
  Outline <- as.matrix(outline)
  SCutfortTest(LD, Outline)
  LDMarray <- SimportMarray(LD, Outline)
  LDsleep <- Sact2sleep(LDMarray)
  LDstat <- SDAMstat(LDMarray, LDsleep, LD, Outline)
  SSavestat(LDstat, Outline, LD)
  Tstat1 <- SstatExclude1(LDstat, Outline)
  Tstat2 <- SstatExclude2(LDstat, Outline)
  StTestGraphActive(Tstat1, Tstat2, outline, LD)
  StTestGraphSleep(Tstat1, Tstat2, outline, LD)
}
