StTest <- function(LD)
{
  library(readxl)
  library(data.table)
  library(ggplot2)
  library(ggsignif)
  summary <- read_excel("summary.xls")
  Summary <- as.matrix(summary)
  SCutfortTest(LD, Summary)
  LDMarray <- SimportMarray(LD, Summary)
  LDsleep <- Sact2sleep(LDMarray)
  LDstat <- SDAMstat(LDMarray, LDsleep, LD)
  SSavestat(LDstat, Summary, LD)
  Tstat1 <- SstatExclude1(LDstat, Summary)
  Tstat2 <- SstatExclude2(LDstat, Summary)
  StTestGraphActive(Tstat1, Tstat2, summary, LD)
  StTestGraphSleep(Tstat1, Tstat2, summary, LD)
}
